### ISSUE TITLE
Add attachToCompileJava/Kotlin flag for gradle 6.x compatibility 

### ISSUE THREAD

**Issue by aldoborrero** [rohanprabhu/kotlin-dsl-gradle-jooq-plugin#13]
Just as has been described in this [PR for the original jooq plugin](https://github.com/etiennestuder/gradle-jooq-plugin/pull/108) it would be nice to be able to disable / enable at will if this plugin attaches itself to `compileKotlin` and `compileJava` tasks.

This allows to run manually `jooq` and to avoid the error that Gradle > 6.0 outputs when you try to delete a dependsOn: `Removing a task dependency from a task instance is not supported`.

**Update**: I added below the PR feel free to review and give suggestions. Thanks!

**Comment by rohanprabhu** [comment]
Thank you for your PR! Really sorry for the extremely delayed response. Will push this in a `0.4.5` release by tomorrow.
